- name: Play for creating container toolboxes using Distrobox or Toolbox
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing create-toolbox.yml as user {{ username }}

    - name: Create general development container with Distrobox
      ansible.builtin.shell: distrobox assemble create --file ./toolbox/fedora-toolbox-generic/fedora-toolbox-generic.ini

    - name: Create gnunet development container with Distrobox
      ansible.builtin.shell: distrobox assemble create --file ./toolbox/fedora-toolbox-gnunet/fedora-toolbox-gnunet.ini

    - name: Create podman-host executable to interact with Podman from inside Flatpak apps
      ansible.builtin.copy:
        dest: ~/.local/bin/podman-host
        content: |
          #!/bin/bash
          set -x

          # This little workaround is used to ensure
          # we use our $USER inside the containers, without
          # resorting to creating devcontainer.json or similar stuff
          arr=("$@")
          for i in "${!arr[@]}"; do
              if [[ ${arr[$i]} == *"root:root"* ]]; then
                  arr[$i]="$(echo "${arr[$i]}" | sed "s|root:root|$USER:$USER|g")"
              fi
          done

          flatpak-spawn --host podman "${arr[@]}"
        mode: u=rx,g=r,o=r
