# This playbook is supposed to be played inside a Toolbox or Distrobox container
- name: Play for installing generic development tools
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing gnunet-toolbox.yml as user {{ username }}

    - name: Install system dependencies
      become: true
      ansible.builtin.dnf:
        name:
          - git
          - gcc
          - gcc-c++
          - clang
          - make
          - gmp
          - gmp-devel
          - ncurses
          - ncurses-compat-libs
          - xz
          - perl
          - zlib-devel
          - openssl
          - openssl-devel
        state: present

    - name: Install PIP packages
      ansible.builtin.pip:
        name:
          - ansible-lint
        executable: pip3
        extra_args: --user

    - name: Install Haskell
      ansible.builtin.shell: |
        set -o pipefail
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_GHC_VERSION=latest BOOTSTRAP_HASKELL_CABAL_VERSION=latest BOOTSTRAP_HASKELL_INSTALL_STACK=1 BOOTSTRAP_HASKELL_INSTALL_HLS=1 BOOTSTRAP_HASKELL_ADJUST_BASHRC=P sh

    - name: Install Rust
      ansible.builtin.shell: |
        set -o pipefail
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Change user shell to fish
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/fish
