- name: Play for configuring the host once basic packages are installed
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing system-ostree-post.yml as user {{ username }}

    - name: Install Homebrew
      ansible.builtin.shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Add Homebrew to bash_profile
      ansible.builtin.lineinfile:
        path: ~/.bash_profile
        line: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    - name: Change user shell to fish
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/fish

    - name: Start systemd services
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - cockpit.socket
        - docker.socket
        - syncthing@{{ ansible_user_id }}
