# https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/apache
services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - ./volumes/data:/var/www/html:z
    networks:
      - restricted
    environment:
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${HOST}:${PORT} # from .env file

  cron:
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - ./volumes/data:/var/www/html:z
    networks:
      - restricted
    entrypoint: /cron.sh
    depends_on:
      - nextcloud

  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/cert.crt:/etc/nginx/cert.crt:z
      - ./nginx/cert.key:/etc/nginx/cert.key:z
    networks:
      - restricted
      - unrestricted
    ports:
      - ${PORT}:443
    depends_on:
      - nextcloud

networks:
  unrestricted:
  restricted:
    internal: true
