- name: Play for configuring the host once basic packages are installed
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing system-ostree-post.yml as user {{ username }}

    - name: Install Nix
      ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

    - name: Start systemd services
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - cockpit.socket
        - docker.socket
        - syncthing@{{ ansible_user_id }}

    - name: Change user shell to fish
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/fish

