- name: Play for layering basic system packages
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing system-ostree.yml as user {{ username }}

    - name: Add Docker CE repository
      become: true
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: u=r,g=r,o=r
        owner: root

    - name: Overlay core packages
      community.general.rpm_ostree_pkg:
        name:
          # fonts
          - adobe-source-sans-pro-fonts
          - fira-code-fonts

          # cockpit
          - cockpit
          - cockpit-system
          - cockpit-ostree
          - cockpit-podman
          - cockpit-machines
          - cockpit-selinux
          - cockpit-networkmanager
          - cockpit-storaged
          - cockpit-sosreport

          # essentials
          - fish
          - syncthing
          - firewall-config
          - tor
          - openssl
          - git
          - gcc
          - make

          # deps for Pano clipboard manager for GNOME
          - libgda
          - libgda-sqlite

          # container tools
          - distrobox
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - kubernetes
        state: present
