# https://github.com/syncthing/syncthing/blob/main/README-Docker.md
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - PCAP=cap_chown,cap_fowner+ep
    volumes:
      - ./volumes/config:/var/syncthing/config
      - ${HOST_DIR}:${MOUNT_POINT}
