# https://github.com/syncthing/syncthing/blob/main/README-Docker.md
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${HOST_DIR}:/var/syncthing
    network_mode: host
    restart: unless-stopped
