version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: 'pihole'
      INTERFACE: wlp2s0
      WEB_PORT: 9091
      PIHOLE_DNS_: 127.0.0.1#5053;::1#5053 # Assuming DNSCrypt is running on port 5053
    volumes:
      - './etc-pihole/:/etc/pihole/:z'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/:z'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped
