services:
  samba:
    build: .
    container_name: samba
    read_only: true
    restart: unless-stopped
    network_mode: host
    environment:
      - SAMBA_USERNAME=${SAMBA_USERNAME}
      - SAMBA_PASSWORD=${SAMBA_PASSWORD}
    tmpfs:
      - /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - ./volumes/config:/etc/samba:ro
      - ${HOST_DIR}:${MOUNT_POINT}
