- name: Play for provisioning homeserver with basic packages
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing system-server.yml as user {{ username }}

    - name: Install dnf-plugins-core
      become: true
      ansible.builtin.shell: dnf -y install dnf-plugins-core

    - name: Add Docker repository
      become: true
      ansible.builtin.shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install essential packages
      become: true
      ansible.builtin.dnf:
        name:
          # essentials
          - fish
          - nano
          - tuned
          - powertop
          - upower

          # network
          - nss-mdns
          - avahi
          - avahi-tools
          - fail2ban

          # cockpit
          - pcp
          - cockpit-pcp
          - cockpit-podman

          # containers
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enabling systemd services
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - docker
        - fail2ban
        - tuned
        - powertop
        - upower
        - avahi

    - name: Configure firewall
      block:
        - name: Configure firewall - Disable SSH on public zone
          ansible.posix.firewalld:
            zone: public
            service: ssh
            permanent: true
            immediate: true
            state: disabled

        - name: Configure firewall - Enable Syncthing
          ansible.posix.firewalld:
            zone: home
            service: syncthing
            permanent: true
            immediate: true
            state: enabled

        - name: Configure mdns
          ansible.posix.firewalld:
            zone: home
            service: mdns
            permanent: true
            immediate: true
            state: enabled

        - name: Configure firewall - Enable HTTPS for Nextcloud
          ansible.posix.firewalld:
            zone: home
            service: https
            permanent: true
            immediate: true
            state: enabled
