- name: Play for layering basic system packages
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing system-ostree.yml as user {{ username }}

    - name: Overlay core packages
      become: true
      community.general.rpm_ostree_pkg:
        name:
          # cockpit
          - cockpit
          - cockpit-system
          - cockpit-ostree
          - cockpit-podman
          - cockpit-machines
          - cockpit-selinux
          - cockpit-networkmanager
          - cockpit-storaged
          - cockpit-sosreport
          - cockpit-files

          # essentials
          - fish
          - lm_sensors
          - tuned
          - powertop
          - smartmontools
          - fail2ban
          - fail2ban-firewalld
          - pass
          - make
          - tailscale
        state: present

    # Fedora Atomic variants does not issue TRIM to SSDs automatically if LVM + LUKS is used
    #    https://bugzilla.redhat.com/show_bug.cgi?id=1801539
    # Fedora Atomic variants does not support BTRFS mount options like compression due to a bug
    #    https://gitlab.com/fedora/ostree/sig/-/issues/72
    #    https://discussion.fedoraproject.org/t/root-mount-options-are-ignored-in-fedora-atomic-desktops-42/148562
    - name: Update kernel args
      become: true
      ansible.builtin.command: rpm-ostree kargs --append-if-missing=rd.luks.options=discard --delete=rootflags=subvol=root --append-if-missing=rootflags=subvol=root,compress=zstd,ro
