- hosts: localhost
  become: no

  collections:
    - community.general
    - ansible.posix

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      debug:
        msg: Playing system-server.yml as user {{ username }}

    - name: Install dnf-plugins-core
      become: yes
      shell: dnf -y install dnf-plugins-core

    - name: Add Docker repository
      become: yes
      shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install essential packages
      become: yes
      dnf:
        name:
          - fish
          - nano
          - tuned
          - powertop
          - upower
          - pcp
          - cockpit-pcp
          - cockpit-podman
          - nss-mdns
          - avahi
          - avahi-tools
          - dnscrypt-proxy
          - fail2ban
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

        state: present

    - name: Enabling systemd services
      become: yes
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - docker
        - fail2ban
        - dnscrypt-proxy
        - tuned
        - powertop
        - upower
        - avahi

    - name: Configure firewall
      block:
        - name: Configure firewall - Disable SSH on public zone
          ansible.posix.firewalld:
            zone: public
            service: ssh
            permanent: yes
            immediate: yes
            state: disabled

        - name: Configure firewall - Enable Syncthing
          ansible.posix.firewalld:
            zone: home
            service: syncthing
            permanent: yes
            immediate: yes
            state: enabled

        - name: Configure firewall - Enable DNS for Pi-Hole
          ansible.posix.firewalld:
            zone: home
            service: dns
            permanent: yes
            immediate: yes
            state: enabled

        - name: Configure mdns
          ansible.posix.firewalld:
            zone: home
            service: mdns
            permanent: yes
            immediate: yes
            state: enabled

        - name: Configure firewall - Enable HTTPS for Nextcloud
          ansible.posix.firewalld:
            zone: home
            service: https
            permanent: yes
            immediate: yes
            state: enabled
