- name: Play for configuring the host once basic packages are installed
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing system-config.yml as user {{ username }}

    - name: Add fail2ban config to jail sshd
      become: true
      ansible.builtin.copy:
        dest: /etc/fail2ban/jail.d/sshd.local
        content: |
          [sshd]
          enabled = true
        mode: u=r,g=r,o=r
        owner: root

    - name: Configure firewall
      block:
        - name: Changing default zone
          become: true
          shell: |
            firewall-cmd --set-default-zone=public
            firewall-cmd --runtime-to-permanent

        - name: Configure firewall to disable services on zone "public"
          become: true
          ansible.posix.firewalld:
            zone: public
            service: "{{ item }}"
            permanent: true
            immediate: true
            state: disabled
          with_items:
            - ssh
            - mdns

        - name: Configure firewall to allow common services on zone "home"
          become: true
          ansible.posix.firewalld:
            zone: home
            service: "{{ item }}"
            permanent: true
            immediate: true
            state: enabled
          with_items:
            - mdns
            - cockpit
            - ssh
            - samba
            - syncthing
            - syncthing-gui

    - name: Start systemd services
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - tuned
        - powertop
        - cockpit.socket
        - sshd.socket
        - fail2ban
