- name: Play for installing flatpak apps on host
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: "Playing apps.yml as user {{ username }}"

    - name: Add Flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: "{{ item }}"
      with_items:
        - user

    - name: Install user applications
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
        remote: flathub
      with_items:
        # Essentials
        - org.keepassxc.KeePassXC
        - org.videolan.VLC

        # Internet
        - org.mozilla.firefox
        - io.gitlab.librewolf-community
        - org.torproject.torbrowser-launcher
        - com.brave.Browser
        - org.gnome.Epiphany
        - org.qbittorrent.qBittorrent
        - org.remmina.Remmina

        # Mail & Messaging
        - org.mozilla.Thunderbird
        - ch.protonmail.protonmail-bridge
        - org.signal.Signal
        - chat.simplex.simplex

        # Knowledge
        - com.calibre_ebook.calibre
        - org.kiwix.desktop

        # Multimedia
        - info.mumble.Mumble
        - org.kde.kdenlive
        - org.tenacityaudio.Tenacity
        - com.obsproject.Studio
        - fr.handbrake.ghb
        - org.kde.gwenview
        - org.kde.digikam
        - org.gpodder.gpodder
        - org.gimp.GIMP
        - org.inkscape.Inkscape

        # Office
        - org.libreoffice.LibreOffice
        - com.github.xournalpp.xournalpp
        - org.kde.okular
        - org.gnucash.GnuCash

        # Utilities
        - com.github.tchx84.Flatseal
        - org.gnome.seahorse.Application
        - org.fedoraproject.MediaWriter
        - org.raspberrypi.rpi-imager
        - io.podman_desktop.PodmanDesktop
