- name: Playbook for installing flatpak apps on host
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg:
          - User - {{ username }}
          - Distribution - {{ ansible_distribution }}
          - Distribution Version - {{ ansible_distribution_major_version }}

    - name: Add Flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: "{{ item }}"
      with_items:
        - user

    - name: Install user applications
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
        remote: flathub
      with_items:
        # Essentials
        - com.nextcloud.desktopclient.nextcloud
        - org.keepassxc.KeePassXC
        - org.videolan.VLC

        # Internet
        - org.mozilla.firefox
        - io.gitlab.librewolf-community
        - org.torproject.torbrowser-launcher
        - com.brave.Browser
        - org.gnome.Epiphany
        - org.qbittorrent.qBittorrent
        - org.remmina.Remmina

        # Mail & Messaging
        - org.mozilla.Thunderbird
        - ch.protonmail.protonmail-bridge
        - org.signal.Signal
        - chat.simplex.simplex

        # Knowledge
        - com.calibre_ebook.calibre
        - org.kiwix.desktop

        # Multimedia
        - info.mumble.Mumble
        - org.kde.kdenlive
        - org.tenacityaudio.Tenacity
        - com.obsproject.Studio
        - fr.handbrake.ghb
        - org.kde.gwenview
        - org.kde.digikam
        - org.gpodder.gpodder
        - org.gimp.GIMP
        - org.inkscape.Inkscape

        # Office
        - org.libreoffice.LibreOffice
        - com.github.xournalpp.xournalpp
        - org.kde.okular
        - org.gnucash.GnuCash

        # System Utilities
        - com.github.tchx84.Flatseal
        - org.gnome.seahorse.Application
        - org.gnome.Extensions
        - org.fedoraproject.MediaWriter
        - org.raspberrypi.rpi-imager
        - io.podman_desktop.PodmanDesktop
        - org.virt_manager.virt-manager
        - org.virt_manager.virt_manager.Extension.Qemu # For QEMU user session
        - com.vscodium.codium

    - name: Override LibreWolf config
      ansible.builtin.copy:
        dest: "/home/{{ username }}/.var/app/io.gitlab.librewolf-community/.librewolf/librewolf.overrides.cfg"
        content: |
          // disable JIT to improve security
          pref("javascript.options.ion", false);
          pref("javascript.options.baselinejit", false);
          pref("javascript.options.wasm", false);
          pref("javascript.options.asmjs", false);
          pref("javascript.options.jit_trustedprincipals", true);

          // reduce frequency of session persistance to increase SSD life
          pref("browser.sessionstore.interval", 1500000);

        mode: u=r,g=r,o=r
        owner: "{{ username }}"
