- name: Play for layering basic system packages
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing system-ostree.yml as user {{ username }}

    - name: Overlay core packages
      community.general.rpm_ostree_pkg:
        name:
          # drivers
          - kmodtool
          - akmods
          - intel-media-driver
          - akmod-nvidia
          - xorg-x11-drv-nvidia
          - xorg-x11-drv-nvidia-cuda
          - xorg-x11-drv-nvidia-cuda-libs
          - xorg-x11-drv-nvidia-power
          - vdpauinfo
          - libva-vdpau-driver
          - libva-utils

          # cockpit
          - pcp
          - cockpit
          - cockpit-system
          - cockpit-ostree
          - cockpit-podman
          - cockpit-machines
          - cockpit-selinux
          - cockpit-pcp
          - cockpit-networkmanager
          - cockpit-storaged
          - cockpit-sosreport

          # containers
          - distrobox

          # vitualization
          - qemu
          - qemu-kvm
          - libvirt-client
          - libvirt-nss
          - libvirt-daemon-kvm
          - libvirt-daemon-config-network
          - libvirt-dbus
          - virt-install
          - virt-viewer
          - virt-manager

           # essentials
          - fish
          - lm_sensors
          - smartmontools
          - firewall-config
          - syncthing
          - nextcloud-client
          - fail2ban
          - fail2ban-firewalld
          - tor
          - openssl
          - tilix
          - https://launchpad.net/veracrypt/trunk/1.26.7/+download/veracrypt-1.26.7-CentOS-8-x86_64.rpm
        state: present

    # This might not be needed at some point when Silverblue will support the standard way to specify this.
    - name: Disable Nouveau drivers
      ansible.builtin.command: rpm-ostree kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1

    # Silverblue does not issue TRIM to SSDs automatically if LVM + LUKS is used. Bug https://bugzilla.redhat.com/show_bug.cgi?id=1801539.
    - name: Enable TRIM on LVM + LUKS - Workaround for bug https://bugzilla.redhat.com/show_bug.cgi?id=1801539
      ansible.builtin.command: rpm-ostree kargs --append-if-missing=rd.luks.options=discard
