- name: Play for ensuring pre-conditions before installing and configuring packages on the host
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing system-ostree-pre.yml as user {{ username }}

    - name: Remove pinned RPM Fusion overlay package
      ansible.builtin.command: rpm-ostree update --uninstall rpmfusion-free-release --uninstall rpmfusion-nonfree-release --install rpmfusion-free-release --install rpmfusion-nonfree-release
