- name: Play for configuring the host once basic packages are installed
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: Playing system-config.yml as user {{ username }}

    - name: Copy Nvidia configuration for customization
      become: true
      ansible.builtin.copy:
        src: /usr/share/X11/xorg.conf.d/nvidia.conf
        dest: /etc/X11/xorg.conf.d/nvidia.conf
        mode: u=rw,g=r,o=r
        owner: root

    # Enable Nvidia DynamicPowerManagement
    # http://download.nvidia.com/XFree86/Linux-x86_64/440.31/README/dynamicpowermanagement.html
    - name: Enable Nvidia Dynamic Power Managment
      become: true
      ansible.builtin.copy:
        dest: "/etc/modprobe.d/nvidia.conf"
        content: "options nvidia NVreg_DynamicPowerManagement=0x02\n"
        mode: u=rw,g=r,o=r
        owner: root

    - name: Create directory for Virtual Machines with CoW disabled
      ansible.builtin.file:
        path: ~/Virtual_Machines
        state: directory
        attributes: +C
        recurse: true

    - name: Add polkit rule to allow Virt-Manager to manage virtual machines
      become: true
      ansible.builtin.copy:
        dest: /etc/polkit-1/rules.d/80-libvirt-manage.rules
        content: |
          polkit.addRule(function(action, subject) {
            if (action.id == "org.libvirt.unix.manage" && subject.local && subject.active && subject.isInGroup("wheel")) {
                return polkit.Result.YES;
            }
          });
        mode: u=r,g=r,o=r
        owner: root

    - name: Configure firewall
      block:
        - name: Configure firewall - Disable SSH on public zone
          ansible.posix.firewalld:
            zone: public
            service: ssh
            permanent: true
            immediate: true
            state: disabled
        - name: Configure firewall - Enable Syncthing
          ansible.posix.firewalld:
            zone: home
            service: syncthing
            permanent: true
            immediate: true
            state: enabled
        - name: Configure firewall - Enable KDEConnect
          ansible.posix.firewalld:
            zone: home
            service: kdeconnect
            permanent: true
            immediate: true
            state: enabled

    - name: Start systemd services
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - cockpit.socket
        - fail2ban
        - syncthing@{{ ansible_user_id }}
