- name: Playbook for installing basic system packages on Fedora Atomic desktops
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg:
          - User - {{ username }}
          - Distribution - {{ ansible_distribution }}
          - Distribution Version - {{ ansible_distribution_major_version }}

    - name: Install basic packages
      become: true
      community.general.rpm_ostree_pkg:
        name:
          # drivers & firmware
          - intel-media-driver
          - libva-utils

          # cockpit
          - cockpit
          - cockpit-system
          - cockpit-ostree
          - cockpit-podman
          - cockpit-machines
          - cockpit-selinux
          - cockpit-networkmanager
          - cockpit-storaged
          - cockpit-files

          # virtualization
          - qemu
          - qemu-kvm
          - libvirt
          - libvirt-nss
          - libvirt-daemon-kvm
          - libvirt-daemon-config-network
          - libvirt-dbus

            # essentials
          - fish
          - lm_sensors
          - powertop
          - smartmontools
          - firewall-config
          - fuse-sshfs
          - fail2ban
          - fail2ban-firewalld
          - tor
          - tailscale
          - syncthing
          - openssl
          - nmap
          - wireshark
          - android-tools
          - gnome-tweaks
          - gnome-shell-extension-system-monitor
          - gnome-shell-extension-drive-menu
        state: present

    - name: Install VeraCrypt
      become: true
      community.general.rpm_ostree_pkg:
        name:
          - https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.24/veracrypt-1.26.24-Fedora-40-x86_64.rpm
        state: present

    # Fedora Atomic variants does not issue TRIM to SSDs automatically if LVM + LUKS is used
    #    https://bugzilla.redhat.com/show_bug.cgi?id=1801539
    # Fedora Atomic variants does not support BTRFS mount options like compression due to a bug
    #    https://gitlab.com/fedora/ostree/sig/-/issues/72
    #    https://discussion.fedoraproject.org/t/root-mount-options-are-ignored-in-fedora-atomic-desktops-42/148562
    - name: Update kernel args
      become: true
      ansible.builtin.command: rpm-ostree kargs --append-if-missing=rd.luks.options=discard --delete=rootflags=subvol=root --append-if-missing=rootflags=subvol=root,compress=zstd,ro
