# This playbook is supposed to be played inside a Toolbox or Distrobox container
- name: Playbook for installing extra tools inside a Toolbox
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg:
          - User - {{ username }}
          - Distribution - {{ ansible_distribution }}
          - Distribution Version - {{ ansible_distribution_major_version }}

    - name: Add RPMFusion repository
      become: true
      block:
        - name: Install GPG and keys
          ansible.builtin.dnf:
            name:
              - gpg
              - distribution-gpg-keys

        - name: Import RPMFusion GPG key
          become: true
          ansible.builtin.rpm_key:
            state: present
            key: "{{ item }}"
          with_items:
            - /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}
            - /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}

        - name: Install RPMFusion repository
          ansible.builtin.dnf:
            name:
              - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
              - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

        - name: Enable fedora-cisco-openh264 repository
          ansible.builtin.command: dnf config-manager setopt fedora-cisco-openh264.enabled=1

    - name: Install essential packages
      become: true
      ansible.builtin.dnf:
        name:
          - fish
          - pip
          - clamav
          - ffmpeg
          - ImageMagick
          - qpdf
        state: present

    - name: Install multimedia codecs
      become: true
      ansible.builtin.dnf:
        name: "@Multimedia"
        state: present

    - name: Install yt-dlp
      become: true
      ansible.builtin.pip:
        name: yt-dlp
        executable: pip3
