# https://containrrr.dev/watchtower/#quick_start
services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro # mount local timezone into the container
    environment:
       WATCHTOWER_CLEANUP: true
       WATCHTOWER_INCLUDE_STOPPED: true
       WATCHTOWER_SCHEDULE: "00 00 04 * * FRI" # Run at 04:00:00 AM Friday
