# https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/apache
services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - ./volumes/data:/var/www/html:z
    environment:
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=sweethome-server # REPLACE HOST

  cron:
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - ./volumes/data:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - nextcloud

  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/cert.pem:/etc/nginx/cert.pem:z
      - ./nginx/cert.key:/etc/nginx/cert.key:z
    ports:
      - 443:443
    depends_on:
      - nextcloud
