version: '3.1'

volumes:
  nextcloud:
  nextcloud-postgres-db:


services:
  db:
    image: postgres:15
    restart: always    
    volumes:
      - nextcloud-postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # REPLACE Password
    
  nextcloud:
    image: nextcloud:latest
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-db-1
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # REPLACE Password
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=sweethome-server.local # REPLACE HOST
      - db

  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/sweethome-server.local.crt:/etc/nginx/sweethome-server.local.crt:z
      - ./nginx/sweethome-server.local.key:/etc/nginx/sweethome-server.local.key:z
    ports:
      - 443:443
    depends_on:
      - nextcloud