- name: Play for installing developer tools
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: "Playing apps.yml as user {{ username }}"

    - name: Add Flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Add Flathub-Beta flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub-beta
        state: present
        flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
        method: user

    - name: Install user applications
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
        remote: flathub
      with_items:
        - com.github.tchx84.Flatseal
        - org.mozilla.firefox
        - im.riot.Riot
        - io.podman_desktop.PodmanDesktop
        - com.visualstudio.code
