- name: Play for installing developer tools
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg: "Playing apps.yml as user {{ username }}"

    - name: Add Flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Add Flathub-Beta flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub-beta
        state: present
        flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
        method: user

    - name: Install user applications
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
        remote: flathub
      with_items:
        - com.github.tchx84.Flatseal
        # Replace Firefox with LibreWolf since Mozilla is becoming hostile towards it's users
        # - org.mozilla.firefox
        - io.gitlab.librewolf-community
        - com.brave.Browser
        - im.riot.Riot
        - io.podman_desktop.PodmanDesktop
        - org.libreoffice.LibreOffice
        - org.videolan.VLC

    - name: Override LibreWolf config
      ansible.builtin.copy:
        dest: "/home/{{ username }}/.var/app/io.gitlab.librewolf-community/.librewolf/librewolf.overrides.cfg"
        content: |
          // disable JIT to improve security
          pref("javascript.options.ion", false);
          pref("javascript.options.baselinejit", false);
          pref("javascript.options.wasm", false);
          pref("javascript.options.asmjs", false);
          pref("javascript.options.jit_trustedprincipals", true);

          // reduce frequency of session persistance to increase SSD life
          pref("browser.sessionstore.interval", 1500000);

        mode: u=r,g=r,o=r
        owner: "{{ username }}"
