- name: Playbook for installing developer tools
  hosts: localhost
  become: false

  vars:
    username: "{{ ansible_user_id }}"

  tasks:
    - name: Echo init message
      ansible.builtin.debug:
        msg:
          - User - {{ username }}
          - Distribution - {{ ansible_distribution }}
          - Distribution Version - {{ ansible_distribution_major_version }}

    - name: Add Flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Add Flathub-Beta flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub-beta
        state: present
        flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
        method: user

    - name: Install apps from flathub-beta
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
        remote: flathub-beta
      with_items:
        - org.mozilla.firefox

    - name: Install apps from flathub
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
        remote: flathub
      with_items:
        - com.github.tchx84.Flatseal
        - com.brave.Browser
        - im.riot.Riot
        - org.libreoffice.LibreOffice
        - org.videolan.VLC
        - org.kde.ark
        - io.podman_desktop.PodmanDesktop
        - org.gnu.emacs
        - io.dbeaver.DBeaverCommunity
        - com.usebruno.Bruno
